# Generated by Django 5.2.16 on 2026-07-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_from',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_to',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slot_duration',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
