# Generated by Django 5.2.16 on 2026-07-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_available_from_doctor_available_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
