# Generated by Django 5.2.16 on 2026-09-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorAppointment',
        ),
    ]
