# Generated by Django 5.2.16 on 2026-09-06 05:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_delete_doctorappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(default=datetime.date.today)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('duration', models.PositiveIntegerField(default=15)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='doctors.doctor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'session_date', 'start', 'end', 'duration'), name='unique_doctor_session_slot')],
            },
        ),
    ]
