# Generated by Django 5.2.16 on 2026-09-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctorsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsession',
            options={'ordering': ['-session_date', '-start']},
        ),
    ]
