# Generated by Django 5.2.16 on 2026-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_appointment_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
